apiVersion: v1
kind: Pod
metadata:
  name: greeterc
  namespace: default
spec:
  containers:
  - env:
    - name: GREETINGS_DELAYMS
      value: "1000"
    - name: GREETINGS_HOST
      value: "greeter"
    - name: GREETINGS_NUMBYTES
      value: "5096"
    - name: GREETINGS_NUMTASKS
      value: "1"
    image: msftmicroservices01.azurecr.io/greeterc:latest
    imagePullPolicy: Always
    name: greeterc
  imagePullSecrets:
  - name: msftmicroservices01
