apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeterd
  name: greeter
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: greeterd
  sessionAffinity: None
  type: ClusterIP