version: '3'
services:

  greeterc:
    image: msftmicroservices01.azurecr.io/greeterc:latest
    depends_on:
      - greeterd
    build: 
      context: .
      dockerfile: Dockerfile.client

  greeterd:
    image: msftmicroservices01.azurecr.io/greeterd:latest
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
     - "3000:3000"
